export const schemesData = [
  {
    name: "PM‑KISAN",
    shortDescription:
      "Income support scheme providing financial assistance to farmers.",
    keyBenefits: "₹6,000/year transferred in three instalments.",
    eligibility: "Small & marginal farmers with cultivable land.",
    applyLink: "https://pmkisan.gov.in/",
    requiredDocs: ["Aadhaar card", "Bank passbook", "Land ownership documents"],
    ytLink: "",
  },
  {
    name: "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
    shortDescription:
      "Crop insurance to protect against natural calamities and crop loss.",
    keyBenefits: "Low premium crop insurance for all farmers.",
    eligibility: "All farmers growing notified crops.",
    applyLink: "https://pmfby.gov.in/",
    requiredDocs: [
      "Land records",
      "Crop details",
      "Kisan Credit Card (if available)",
    ],
    ytLink: "",
  },
  {
    name: "Soil Health Card Scheme",
    shortDescription: "Free soil testing and advisory to enhance productivity.",
    keyBenefits: "Soil quality report that suggests nutrient requirements.",
    eligibility: "All farmers with cultivable land.",
    applyLink: "https://soilhealth.dac.gov.in/",
    requiredDocs: ["Farm survey number", "Aadhaar card"],
    ytLink: "",
  },
  {
    name: "Kisan Credit Card (KCC)",
    shortDescription:
      "Credit facility at cheaper interest rates for farming needs.",
    keyBenefits: "Short‑term crop production loans & allied benefits.",
    eligibility: "Farmers with land documents or leasing agreements.",
    applyLink: "https://kisancreditcard.com/",
    requiredDocs: ["Land records", "Identity & address proof"],
    ytLink: "",
  },
  {
    name: "PMKSY (Pradhan Mantri Krishi Sinchayee Yojana)",
    shortDescription: "Water‑use efficient irrigation schemes.",
    keyBenefits: "Boosts irrigation coverage & use of water.",
    eligibility: "All farmers with irrigation needs.",
    applyLink: "https://pmksy.gov.in/",
    requiredDocs: ["Land records", "Irrigation plan (if required)"],
    ytLink: "",
  },
  {
    name: "PM KUSUM Scheme",
    shortDescription: "Solar pumps & renewable energy support for farmers.",
    keyBenefits: "Subsidised solar pumps & opportunity to sell surplus power.",
    eligibility: "All farmers & agri pumps owners.",
    applyLink: "https://mnre.gov.in/en/solar‑energy/schemes/pmmky",
    requiredDocs: ["Aadhaar card", "Land/ Pump ownership proof"],
    ytLink: "",
  },
  {
    name: "Agriculture Infrastructure Fund (AIF)",
    shortDescription: "Financing support for post‑harvest infrastructure.",
    keyBenefits: "Loans for cold storage, silos, packhouses.",
    eligibility: "FPOs, cooperatives, farmers & startups.",
    applyLink: "https://agricultureinfraempower.gov.in/",
    requiredDocs: [
      "Project report",
      "Land documents",
      "Business proof (for enterprises)",
    ],
    ytLink: "",
  },
  {
    name: "e‑NAM (National Agriculture Market)",
    shortDescription: "Online trading platform to improve market transparency.",
    keyBenefits: "Better price discovery & wider mandi access.",
    eligibility: "All farmers & traders in mandi zones.",
    applyLink: "https://e‑NAM‑gov.in/",
    requiredDocs: ["Aadhaar", "Mandi/Trade licence (if required)"],
    ytLink: "",
  },
  {
    name: "National Agriculture Insurance Scheme",
    shortDescription: "State/central coordinated crop insurance framework.",
    keyBenefits: "Protection against crop loss risks.",
    eligibility: "All farmers growing notified crops.",
    applyLink: "https://pmfby.gov.in/",
    requiredDocs: [
      "Land records",
      "Crop details",
      "KCC details (if available)",
    ],
    ytLink: "",
  },
  {
    name: "Pradhan Mantri Kisan Maan‑Dhan Yojana",
    shortDescription: "Pension scheme for small & marginal farmers.",
    keyBenefits: "₹3,000/month pension after age 60.",
    eligibility: "Small & marginal farmers aged 18‑40.",
    applyLink: "https://www.pmkmy.gov.in/",
    requiredDocs: ["Aadhaar card", "Bank account passbook", "Land/farm proofs"],
    ytLink: "",
  },
  {
    name: "Gramin Bhandaran Yojana",
    shortDescription: "Subsidised rural godown/storage facilities.",
    keyBenefits: "Reduced post‑harvest losses.",
    eligibility: "Cooperatives & rural entrepreneurs.",
    applyLink: "https://mofpi.nic.in/en/schemes/grameen‑bhandaran‑yojana",
    requiredDocs: ["Business/ Coop registration proof"],
    ytLink: "",
  },
  {
    name: "Micro Irrigation Fund (NABARD)",
    shortDescription: "Micro‑irrigation support via subsidised loans.",
    keyBenefits: "Encourages drip/sprinkler irrigation.",
    eligibility: "All farmers & farmer groups.",
    applyLink: "https://www.nabard.org/content1.aspx?id=564",
    requiredDocs: ["Land records", "Project application"],
    ytLink: "",
  },
  {
    name: "Rashtriya Krishi Vikas Yojana (RKVY)",
    shortDescription: "State‑level agriculture development scheme.",
    keyBenefits: "State sponsored agri projects & support.",
    eligibility: "Farmers & farm groups based on state guidelines.",
    applyLink: "https://rkvy.nic.in/",
    requiredDocs: ["State specific"],
    ytLink: "",
  },
  {
    name: "National Horticulture Mission",
    shortDescription: "Promotion of horticulture & allied activities.",
    keyBenefits: "Support for fruits, vegetables & plantations.",
    eligibility: "Horticulture farmers & associations.",
    applyLink: "https://hortnet.gov.in/en/HM.aspx",
    requiredDocs: ["Farm survey details", "Identity & land proofs"],
    ytLink: "",
  },
  {
    name: "Integrated Scheme on Agriculture Marketing",
    shortDescription: "Improve agri marketing infrastructure & logistics.",
    keyBenefits: "Better storage, collection & market flow.",
    eligibility: "State market federations, cooperatives.",
    applyLink: "https://dacnet.nic.in/ecirculars/2024/ISAM.pdf",
    requiredDocs: ["State/ Market proposal docs"],
    ytLink: "",
  },
];
